version: '3'

services:
  backservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

  ui:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=Tracker;user=sa;password=Tracker1234$$;MultipleActiveResultSets=true"
    ports:
      - "5004:80"

  db:
    environment:
      SA_PASSWORD: "Tracker1234$$"
      ACCEPT_EULA: "Y"